##################################################################################
#         Calls workflow from code repo
##################################################################################
name: Android - Release to Google Play

on:
  workflow_dispatch:

jobs:
  android_release:
    uses: IDEMSInternational/open-app-builder/.github/workflows/reusable-android-release.yml@master
    secrets:
      FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      ALIAS: ${{ secrets.ALIAS }}
      KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
