##################################################################################
#         Calls workflow from code repo
##################################################################################
name: Deploy - Firebase

on:
  push:
    branches:
      - "main"

jobs:
  web_preview:
    uses: IDEMSInternational/open-app-builder/.github/workflows/reusable-deploy-web-preview.yml@master
    secrets:
      FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
